name: CI

on:
  push:
    branches:
      - main
    run:
  pull-request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Installs required OS package dependencies and npm dependencies
        run: npm install
      - name: Runs all tests
        run: npm run test